# Generated by Django 4.2 on 2023-05-05 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("instructor", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("site", models.CharField(max_length=400)),
                ("url", models.URLField(max_length=500)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "rating",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=13, null=True
                    ),
                ),
                (
                    "thumbnail_url",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                ("is_package", models.BooleanField(default=False)),
                ("is_free", models.BooleanField(default=False)),
                ("enrollment_count", models.IntegerField(default=0)),
                (
                    "tags",
                    models.ManyToManyField(
                        related_name="course_tags", to="courses.tag"
                    ),
                ),
            ],
        ),
    ]
