# Generated by Django 4.2 on 2023-05-06 11:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="dislikes",
            field=models.ManyToManyField(
                related_name="disliked_courses", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="likes",
            field=models.ManyToManyField(
                related_name="liked_courses", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
