# Generated by Django 4.2 on 2023-05-06 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_course_dislikes_course_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="update_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="instructor",
            field=models.CharField(max_length=32),
        ),
    ]
