# Generated by Django 4.2 on 2023-05-06 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("series", "0003_series_create_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="series",
            name="create_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
