
tag_mapping = { 
        '': '없음',  
        ' 재테크': 'finance',  
        '3d 모델링': '3d modeling',  
        'IoT': 'iot',  
        'angular': 'angular.js',  
        'apache spark': 'spark',  
        'boot': 'spring boot',  
        'confluence cloud': 'confluence',  
        'continuous': 'ci/cd',  
        'extjs': 'ext.js',  
        'html': 'html/css',  
        'integration': 'ci/cd',  
        'intellij idea': 'intellij',  
        'ios autolayout': 'ios',  
        'it 서비스 관리': 'it service management',  
        'junit5': 'junit',  
        'language': 'programming language',  
        'learn': 'education',  
        'microsoft windows': 'windows',  
        'nestjs': 'next.js',  
        'pc정비사': 'pc mechanic',  
        'pl/sql': 'sql',  
        'python3': 'python',  
        'query': 'sql',  
        'react context': 'react',  
        'react native': 'react',  
        'ruby on rails': 'ruby',  
        'streamlit': 'stream',  
        'swiftui': 'swift',   
        'three': 'three.js',  
        'travis ci': 'travis',  
        'unity ml': 'unity',  
        'visual studio code': 'vscode',  
        'vue': 'vue.js',  
        'windows server': 'windows',  
        '가상화': 'virtualization',  
        '강화학습': 'education',  
        '개발 도구': 'develop tool',  
        '개발도구': 'develop tool',  
        '개인 브랜딩': 'personal branding',  
        '객체지향': 'object oriented',  
        '게임 개발': 'game developing',  
        '게임 기획': 'game planning',  
        '게임 아트' : 'game art',
        '게임 프로그래밍' : 'game programming',
        '게임개발' : 'game developing',
        '게임기획' : 'game planning',
        '게임수학' : 'game math',
        '게임개론' : 'game',
        '고급' : 'advanced',
        '관점지향' : 'aspect oriented',
        '교양' : 'culture',
        '구글 앱 엔진' : 'google app engine',
        '그래픽' : 'graphic',
        '금융' : 'finance',
        '기술면접' : 'job',
        '기타' : 'etc',
        '기획' : 'service planning',
        '네트워크' : 'network',
        '넥사크로' : 'nexacro',
        '다트' : 'dart',
        '데브옵스' : 'devops',
        '데스크톱 앱 개발' : 'desktop app',
        '데이터 분석' : 'data analysis',
        '데이터 사이언스' : 'data science',
        '데이터 수집' : 'data engineering',
        '데이터 시각화' : 'data visualization',
        '데이터 엔지니어링' : 'data engineering',
        '데이터베이스' : 'database',
        '데이터분석' : 'data analysis',
        '데이터추출/분석' : 'data analysis',
        '도메인' : 'domain',
        '도커' : 'docker',
        '동시성' : 'concurrency',
        '드론 개발' : 'drone',
        '디자인 시스템' : 'design',
        '디자인 툴' : 'design',
        '디자인 패턴' : 'design',
        '디지털 리터러시' : 'digital literacy',
        '디지털 마케팅' : 'digital marketing',
        '딥러닝' : 'deep learning',
        '라라벨' : 'laravel',
        '레일즈' : 'ruby',
        '루비' : 'ruby',
        '리눅스' : 'linux',
        '리액트' : 'react',
        '리팩토링' : 'refactoring',
        '마케팅' : 'marketing',
        '머신러닝' : 'machine learning',
        '메타버스' : 'metaverse',
        '면접' : 'job',
        '모바일 앱 디자인' : 'mobile design',
        '모바일 디자인' : 'mobile design',
        '모바일 앱 개발' : 'mobile app developing',
        '모바일프로그래밍' : 'mobile programming',
        '모빌리티' : 'mobility',
        '모의해킹' : 'hacking',
        '반응형 웹' : 'web',
        '백엔드' : 'backend',
        '버전관리시스템' : 'version control',
        '병렬 처리' : 'handling',
        '보안' : 'security',
        '보통' : 'intermediate',
        '부트스트랩' : 'bootstrap',
        '블로그' : 'blog',
        '블록체인' : 'blockchain',
        '블록코딩' : 'coding',
        '블록프로그래밍' : 'programming',
        '빅데이터' : 'big data',
        '서버리스' : 'serverless',
        '서비스 기획' : 'service planning',
        '선형대수학' : 'math',
        '소프트웨어 설계' : 'software',
        '소프트웨어 테스트' : 'software',
        '수학' : 'math',
        '쉬움' : 'beginner',
        '스크래치' : 'scratch',
        '스프링' : 'spring',
        '시빅해킹' : 'hacking',
        '시스템' : 'system',
        '아두이노' : 'aduino',
        '아키텍처' : 'architecture',
        '아토믹 디자인' : 'design',
        '안드로이드' : 'android',
        '알고리즘' : 'algorithm',
        '애자일' : 'agile',
        '앵귤러' : 'angular.js',
        '양자 컴퓨팅' : 'computer',
        '어려움' : 'advanced',
        '언리얼 c++' : 'c++',
        '업무 생산성' : 'productivity',
        '업무 자동화' : 'automation',
        '엑셀' : 'excel',
        '엔트리' : 'entry',
        '영상제작' : 'video',
        '오피스' : 'office',
        '온라인 교육' : 'education',
        '운영체제' : 'os',
        '웹 개발' : 'web developing',
        '웹 디자인' : 'web design',
        '웹 크롤링' : 'web crawling',
        '웹 퍼블리싱' : 'web publishing',
        '웹앱' : 'web',
        '웹프로그래밍' : 'web',
        '웹 스크래핑' : 'web scraping',
        '윈도우' : 'windows',
        '유니티' : 'unity',
        '유닉스' : 'unix',
        '이력서' : 'job',
        '이직' : 'job',
        '인공신경망' : 'ai',
        '인공지능' : 'ai',
        '인터랙티브 웹' : 'web',
        '인프라' : 'infrastructure',
        '임베디드' : 'embedded',
        '입문' : 'beginner',
        '자격증' : 'license',
        '자동화' : 'automation',
        '자료구조' : 'data structure',
        '자바' : 'typescript',
        '자바스크립트' : 'javascript',
        '장고' : 'django',
        '전략' : 'strategy',
        '정규식' : 'regex',
        '중급' : 'intermediate',
        '중급이상' : 'advanced',
        '직무분석' : 'job',
        '차트분석' : 'finance',
        '처리' : 'handling',
        '초급' : 'beginner',
        '추천 시스템' : 'recommender',
        '취업' : 'job',
        '커뮤니케이션' : 'communication',
        '컴퓨터 구조' : 'computer',
        '컴퓨터 비전' : 'computer',
        '컴퓨터활용능력' : 'computer',
        '코딩 테스트' : 'coding test',
        '코틀린' : 'kotlin',
        '콘텐츠 기획' : 'typescript',
        '콘텐츠 제작' : 'contents',
        '퀀트' : 'finance',
        '클라우드' : 'cloud',
        '클론코딩' : 'clone coding',
        '타입스크립트' : 'typescript',
        '텍스트마이닝' : 'text mining',
        '텐서플로우' : 'tensorflow',
        '통계' : 'statistics',
        '투자' : 'finance',
        '파이썬' : 'python',
        '파이어베이스' : 'firebase',
        '퍼포먼스 마케팅' : 'marketing',
        '포트폴리오' : 'portfolio',
        '풀스택' : 'fullstack',
        '프로그래밍':'programming',
        '프로그래밍 언어':'programming language',
        '프로그래밍교양':'programming basic',
        '프로그래밍기초':'programming basic',
        '프로그래밍 기초':'programming basic',
        '프로토콜':'protocol',
        '프로토타이핑':'prototyping',
        '프론트엔드':'frontend',
        '프로젝트 관리':'project management',
        '플라스크':'flask',
        '플러터':'flutter',
        '하이브리드 앱':'hybrid app',
        '함수형 프로그래밍':'programming',
        '해킹':'hacking',
        '행렬':'matrix',
        '협업 툴':'collaboration tool',
    }